export const mascotArtwork = {
    'step-love': {
        src: '/images/mascots/step-love-720.webp',
        srcset: '/images/mascots/step-love-360.webp 360w, /images/mascots/step-love-720.webp 720w',
        mask: '/images/mascots/step-love-outline.svg',
        width: 720,
        height: 720,
    },
    'step-roll': {
        src: '/images/mascots/step-roll-720.webp',
        srcset: '/images/mascots/step-roll-360.webp 360w, /images/mascots/step-roll-720.webp 720w',
        mask: '/images/mascots/step-roll-outline.svg',
        width: 720,
        height: 720,
    },
    'step-grill': {
        src: '/images/mascots/step-grill-720.webp',
        srcset: '/images/mascots/step-grill-360.webp 360w, /images/mascots/step-grill-720.webp 720w',
        mask: '/images/mascots/step-grill-outline.svg',
        width: 720,
        height: 720,
    },
    grill: {
        src: '/images/mascots/grill-720.webp',
        srcset: '/images/mascots/grill-360.webp 360w, /images/mascots/grill-720.webp 720w',
        mask: '/images/mascots/grill-outline.svg',
        width: 720,
        height: 913,
    },
    choose: {
        src: '/images/mascots/choose-720.webp',
        srcset: '/images/mascots/choose-360.webp 360w, /images/mascots/choose-720.webp 720w',
        mask: '/images/mascots/choose-outline.svg',
        width: 720,
        height: 913,
    },
    deliver: {
        src: '/images/mascots/deliver-720.webp',
        srcset: '/images/mascots/deliver-360.webp 360w, /images/mascots/deliver-720.webp 720w',
        mask: '/images/mascots/deliver-outline.svg',
        width: 720,
        height: 913,
    },
    gift: {
        src: '/images/mascots/gift-720.webp',
        srcset: '/images/mascots/gift-360.webp 360w, /images/mascots/gift-720.webp 720w',
        mask: '/images/mascots/gift-outline.svg',
        width: 720,
        height: 913,
    },
    curious: {
        src: '/images/mascots/curious-720.webp',
        srcset: '/images/mascots/curious-360.webp 360w, /images/mascots/curious-720.webp 720w',
        mask: '/images/mascots/curious-outline.svg',
        width: 720,
        height: 913,
    },
    announce: {
        src: '/images/mascots/announce-720.webp',
        srcset: '/images/mascots/announce-360.webp 360w, /images/mascots/announce-720.webp 720w',
        mask: '/images/mascots/announce-outline.svg',
        width: 720,
        height: 913,
    },
} as const;
