<?php

return [
    'products' => [
        [
            'slug' => 'the-regular',
            'name' => 'The Big Wiener Club',
            'price' => 5900,
            'category' => 'subscription',
            'eyebrow' => 'Membership has its perks. Mostly sausages.',
            'colour' => 'mustard',
            'cadence' => 'monthly',
            'story' => 'Your next BBQ, on repeat. A rotating discovery box for people who take their sausage seriously.',
            'highlights' => ['Rotating sausage selection', 'A little recipe inspiration', 'Monthly delivery proposed'],
            'contents' => ['A curated mix of German-style sausage packs', 'A recipe card with a fresh serving idea'],
            'featured' => true,
        ],
        [
            'slug' => 'the-fling',
            'name' => 'The Wurst Fling',
            'price' => 6500,
            'category' => 'box',
            'eyebrow' => 'Big flavour. No strings attached.',
            'colour' => 'sage',
            'cadence' => 'one-off',
            'story' => 'All the good stuff, just this once. Meet your next favourite without making it a monthly thing.',
            'highlights' => ['One-off discovery box', 'Made for curious appetites', 'No ongoing commitment'],
            'contents' => ['A curated mix of German-style sausage packs', 'Ideas for your next cook-up'],
            'featured' => true,
        ],
        [
            'slug' => 'the-big-gesture',
            'name' => 'Nice Package',
            'price' => 7900,
            'category' => 'gift',
            'eyebrow' => 'Say it with sausages.',
            'colour' => 'peach',
            'cadence' => 'one-off',
            'story' => 'Flowers are lovely. Sausages are dinner. A generous gift box for your favourite grill enthusiast.',
            'highlights' => ['A one-off gift box', 'Gift note planned for launch', 'Ridiculously good gifting'],
            'contents' => ['A generous German-style sausage selection', 'A personal gift note at launch'],
            'featured' => true,
        ],
        [
            'slug' => 'classic-wieners',
            'name' => 'Classic Wieners',
            'price' => 850,
            'category' => 'pack',
            'eyebrow' => 'THE ORIGINAL CROWD-PLEASER',
            'colour' => 'mustard',
            'cadence' => 'one-off',
            'story' => 'A familiar favourite for hot dogs, quick dinners and one-more-bite moments.',
            'highlights' => ['Individual pack concept', 'German-style favourite', 'Final size to be confirmed'],
            'contents' => ['One sausage pack; size, ingredients and allergens pending supplier confirmation'],
            'featured' => false,
        ],
        [
            'slug' => 'bratwurst',
            'name' => 'Bratwurst',
            'price' => 890,
            'category' => 'pack',
            'eyebrow' => 'MEET YOUR GRILL FRIEND',
            'colour' => 'sage',
            'cadence' => 'one-off',
            'story' => 'The classic German-style grill companion. Bring the mustard and make an afternoon of it.',
            'highlights' => ['Individual pack concept', 'A BBQ staple', 'Final size to be confirmed'],
            'contents' => ['One sausage pack; size, ingredients and allergens pending supplier confirmation'],
            'featured' => false,
        ],
        [
            'slug' => 'cheese-kransky',
            'name' => 'Cheese Kransky',
            'price' => 990,
            'category' => 'pack',
            'eyebrow' => 'A LITTLE EXTRA CHEESY',
            'colour' => 'peach',
            'cadence' => 'one-off',
            'story' => 'For the cheese-in-everything crowd. A hearty contender for the best thing on the BBQ.',
            'highlights' => ['Individual pack concept', 'For cheese lovers', 'Final size to be confirmed'],
            'contents' => ['One sausage pack; size, ingredients and allergens pending supplier confirmation'],
            'featured' => false,
        ],
    ],
];
